# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'ITinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ITinder

  pod 'DeviceKit', '~> 4.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Shuffle-iOS'
  pod 'PopBounceButton'
  pod 'Kingfisher', '~> 6.0.1'
  pod 'MessageKit', '~> 3.3.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5.6'
  pod 'SwiftLint'
  pod 'SwiftMessages'

end
